sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t treborium/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true treborium/docker-react yarn test --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-173281565785"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
